from selenium import webdriver
options = webdriver.ChromeOptions()
# user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
# options.add_argument(f'user-agent={user_agent}')
options.add_argument("--headless")
options.add_argument("--window-size=1920,1080")
options.add_argument('--ignore-certificate-errors')
options.add_argument('--allow-running-insecure-content')
options.add_argument("--disable-extensions")
options.add_argument("--proxy-server='direct://'")
options.add_argument("--proxy-bypass-list=*")
options.add_argument("--start-maximized")
options.add_argument('--disable-gpu')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
options.add_argument("enable-automation")
options.add_argument("--disable-infobars")
driver = webdriver.Chrome(options=options)
driver.get("https://youtube.com/")
driver.get_screenshot_as_file("ss.png")
print(driver.title)
